[AP-25]-request-book
archis-academy/April-Backend-Subs-1 pull request #14
Opened 2024-05-11 15:52 UTC by Berkansevil

2024-05-13 00:59 UTC, emineaycakul approved these changes

2024-05-13 15:12 UTC, JamshidS requested changes

2024-05-13 15:12 UTC, JamshidS commented on src/LibraryManagementSystem.java
> +	public static void requestBook(String ISBN){
```suggestion
	public static void requestBook(String bookName){
```

2024-05-15 15:13 UTC, JamshidS approved these changes

2024-05-15 15:13 UTC, merged