[AP-6]-View available books method
archis-academy/April-Backend-Subs-1 pull request #4
Opened 2024-05-04 12:24 UTC by Berkansevil

2024-05-04 13:06 UTC, emineaycakul approved these changes

2024-05-06 11:07 UTC, JamshidS requested changes

2024-05-06 11:07 UTC, JamshidS commented on src/LibraryManagementSystem.java
> +        boolean b=true;
```suggestion
        boolean isEmpty=true;
```

2024-05-08 15:27 UTC, JamshidS approved these changes

2024-05-08 15:27 UTC, merged